base_url = "https://coderdojovr.nexxontech.it"
minify_html = true
ignored_static = [ ".gitignore", "*.src.css", "*.mjs" ]

[markdown]
highlight_code = true

[extra]
dates = [
    "2026-09-19", "2026-10-03", "2026-10-17", "2026-11-07", "2026-11-21", "2026-12-05", "2026-12-19"
]

navbar_items = [
    { title = "Chi siamo?", url = "/chi-siamo" },
    { title = "FAQs", url = "/faq" },
    { title = "Contatti", url = "/contatti" },
    { title = "Risorse", url = "/risorse" },
    { title = "Diventa Mentor", url = "/diventa-mentor" },
]
